const TOOLS=[
{id:'merge',icon:'⤧',name:'合併 PDF',cat:'整理',desc:'將多份 PDF 按次序合成一份',accepts:'application/pdf',multiple:true,color:'#2563eb'},
{id:'split',icon:'✂',name:'分割 PDF',cat:'整理',desc:'按頁碼範圍輸出多份 PDF ZIP',accepts:'application/pdf',multiple:false,color:'#7c3aed'},
{id:'extract',icon:'⇧',name:'提取頁面',cat:'整理',desc:'將指定頁面抽出成新 PDF',accepts:'application/pdf',multiple:false,color:'#0ea5e9'},
{id:'delete',icon:'⌫',name:'刪除頁面',cat:'整理',desc:'移除指定頁面並輸出新 PDF',accepts:'application/pdf',multiple:false,color:'#e11d48'},
{id:'rotate',icon:'↻',name:'旋轉頁面',cat:'整理',desc:'全部或指定頁面旋轉 90° / 180° / 270°',accepts:'application/pdf',multiple:false,color:'#f59e0b'},
{id:'reorder',icon:'≡',name:'重新排序',cat:'整理',desc:'用頁碼次序快速重排 PDF',accepts:'application/pdf',multiple:false,color:'#64748b'},
{id:'img2pdf',icon:'▧',name:'圖片轉 PDF',cat:'轉換',desc:'JPG / PNG 多圖合成 PDF',accepts:'image/jpeg,image/png',multiple:true,color:'#16a34a'},
{id:'pdf2img',icon:'▤',name:'PDF 轉圖片',cat:'轉換',desc:'逐頁轉 PNG / JPEG 並打包 ZIP',accepts:'application/pdf',multiple:false,color:'#0891b2'},
{id:'watermark',icon:'◒',name:'文字水印',cat:'編輯',desc:'加入可顯示中文的半透明文字水印',accepts:'application/pdf',multiple:false,color:'#db2777'},
{id:'pagenum',icon:'123',name:'新增頁碼',cat:'編輯',desc:'頁底 / 頁頂加入頁碼',accepts:'application/pdf',multiple:false,color:'#9333ea'},
{id:'metadata',icon:'i',name:'清理 Metadata',cat:'清理',desc:'清空常見文件描述 Metadata',accepts:'application/pdf',multiple:false,color:'#059669'},
{id:'info',icon:'⌁',name:'PDF 資料',cat:'檢視',desc:'查看頁數、尺寸及常見 Metadata',accepts:'application/pdf',multiple:false,color:'#475569'}];
const state={tool:null,files:[],result:null,resultName:'',processing:false,cancel:false,deferredPrompt:null};
const $=s=>document.querySelector(s);
const els={grid:$('#toolGrid'),search:$('#searchInput'),count:$('#toolCount'),dialog:$('#toolDialog'),category:$('#dialogCategory'),title:$('#dialogTitle'),description:$('#dialogDescription'),drop:$('#dropZone'),input:$('#fileInput'),list:$('#fileList'),options:$('#optionsPanel'),process:$('#processBtn'),cancel:$('#cancelBtn'),close:$('#closeDialogBtn'),warning:$('#warningBox'),progressWrap:$('#progressWrap'),progress:$('#progressBar'),progressText:$('#progressText'),progressPct:$('#progressPct'),result:$('#resultBox'),resultName:$('#resultName'),resultMeta:$('#resultMeta'),download:$('#downloadBtn'),share:$('#shareBtn'),toast:$('#toast'),theme:$('#themeBtn'),install:$('#installBtn')};
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2200)}
function formatBytes(n){const u=['B','KB','MB','GB'];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i?1:0)} ${u[i]}`}
function safeName(name){return name.replace(/\.[^.]+$/,'').replace(/[^\w\u3400-\u9fff-]+/g,'_').slice(0,70)||'document'}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderTools(filter=''){const q=filter.trim().toLowerCase();const tools=TOOLS.filter(t=>!q||`${t.name} ${t.cat} ${t.desc}`.toLowerCase().includes(q));els.count.textContent=`${tools.length} 個`;els.grid.innerHTML=tools.length?tools.map(t=>`<button class="tool-card" type="button" data-tool="${t.id}" style="--tool-color:${t.color}"><div class="tool-icon">${t.icon}</div><b>${t.name}</b><span>${t.desc}</span></button>`).join(''):`<div class="empty-state">搵唔到相關工具。</div>`;els.grid.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.tool))}
function openTool(id){state.tool=TOOLS.find(t=>t.id===id);state.files=[];clearResult();state.cancel=false;els.category.textContent=state.tool.cat;els.title.textContent=state.tool.name;els.description.textContent=state.tool.desc;els.input.accept=state.tool.accepts;els.input.multiple=state.tool.multiple;$('#dropTitle').textContent=state.tool.multiple?'選擇一個或多個文件':'選擇一個文件';$('#dropHint').textContent=state.tool.id==='merge'?'檔案會按你加入的次序合併':'點按選擇，或拖放檔案到此處';renderFiles();renderOptions();updateWarning();els.dialog.showModal()}
function closeDialog(){if(state.processing){toast('請先取消或完成處理');return}els.dialog.close();state.files=[];clearResult()}
function addFiles(fileList){const incoming=[...fileList];if(!state.tool.multiple&&incoming.length>1)incoming.splice(1);if(!state.tool.multiple)state.files=[];const accepts=state.tool.accepts.split(',');for(const f of incoming){const ext=f.name.toLowerCase().split('.').pop();const okay=accepts.some(a=>a===f.type)||(accepts.includes('application/pdf')&&ext==='pdf')||(accepts.includes('image/jpeg')&&['jpg','jpeg'].includes(ext))||(accepts.includes('image/png')&&ext==='png');if(okay)state.files.push(f);else toast(`不支援：${f.name}`)}renderFiles();updateWarning();clearResult()}
function renderFiles(){els.list.innerHTML=state.files.map((f,i)=>`<div class="file-row"><div class="file-kind">${f.type.includes('pdf')?'PDF':'IMG'}</div><div class="file-name"><b>${escapeHtml(f.name)}</b><span>${formatBytes(f.size)}</span></div><button class="remove-file" type="button" data-i="${i}" aria-label="移除">×</button></div>`).join('');els.list.querySelectorAll('.remove-file').forEach(b=>b.onclick=()=>{state.files.splice(Number(b.dataset.i),1);renderFiles();updateWarning();clearResult()})}
function field(label,html,help=''){return `<label class="field"><span>${label}</span>${html}${help?`<small>${help}</small>`:''}</label>`}
function renderOptions(){let h='';switch(state.tool.id){case'split':h=field('分割範圍','<textarea id="ranges" placeholder="例如：1-3, 4-6, 7, 8-10"></textarea>','每個逗號區段會輸出成獨立 PDF，最後打包 ZIP。');break;case'extract':case'delete':h=field('頁碼','<input id="pages" inputmode="numeric" placeholder="例如：1-3,5,8">','頁碼由 1 開始，可使用範圍。');break;case'rotate':h=`<div class="inline-fields">${field('旋轉角度','<select id="angle"><option>90</option><option>180</option><option>270</option></select>')}${field('頁面','<input id="pages" placeholder="留空 = 全部">')}</div>`;break;case'reorder':h=field('新頁面次序','<textarea id="order" placeholder="例如：3,1,2,4-8"></textarea>','必須剛好包含原 PDF 每一頁一次。');break;case'img2pdf':h=`<div class="inline-fields">${field('頁面尺寸','<select id="pageSize"><option value="image">跟圖片比例</option><option value="a4">A4</option></select>')}${field('邊距','<select id="margin"><option value="0">0</option><option value="18">18 pt</option><option value="36">36 pt</option></select>')}</div>`;break;case'pdf2img':h=`<div class="inline-fields">${field('格式','<select id="imageType"><option value="png">PNG</option><option value="jpeg">JPEG</option></select>')}${field('清晰度','<select id="scale"><option value="1">1×</option><option value="1.5" selected>1.5×</option><option value="2">2×</option></select>')}</div>`;break;case'watermark':h=field('水印文字','<input id="watermarkText" maxlength="80" value="CONFIDENTIAL">')+`<div class="inline-fields">${field('透明度','<input id="opacity" type="number" min="0.05" max="0.9" step="0.05" value="0.18">')}${field('旋轉','<select id="wmRotate"><option value="-35">-35°</option><option value="0">0°</option><option value="35">35°</option></select>')}</div>`;break;case'pagenum':h=`<div class="inline-fields">${field('位置','<select id="position"><option value="bottom-center">頁底中央</option><option value="bottom-right">頁底右方</option><option value="top-center">頁頂中央</option></select>')}${field('格式','<select id="numFormat"><option value="n">1</option><option value="n-total">1 / 10</option><option value="page-n">Page 1</option></select>')}</div>`;break;case'metadata':h='<div class="warning-box">會清空 Title、Author、Subject、Keywords、Creator、Producer，並重設修改日期。這不等於完整 forensic sanitization。</div>';break;case'info':h='<div id="infoOutput" class="warning-box">加入 PDF 後按「讀取資料」。</div>';break}els.options.innerHTML=h;els.process.textContent=state.tool.id==='info'?'讀取資料':'開始處理'}
function updateWarning(){const total=state.files.reduce((s,f)=>s+f.size,0);let msg='';if(total>200*1024*1024)msg='⛔ 檔案總大小超過 200 MB。為避免手機 browser 因記憶體不足被系統終止，本版本會拒絕處理。';else if(total>80*1024*1024)msg='⚠️ 檔案總大小超過 80 MB。手機 Safari / Chrome 可能需要大量 RAM，建議關閉其他分頁。';els.warning.hidden=!msg;els.warning.textContent=msg}
function setProgress(p,text='處理中…'){els.progressWrap.hidden=false;els.progress.value=p;els.progressPct.textContent=`${Math.round(p)}%`;els.progressText.textContent=text}
function clearProgress(){els.progressWrap.hidden=true;els.progress.value=0}
function clearResult(){if(state.result?.url)URL.revokeObjectURL(state.result.url);state.result=null;state.resultName='';els.result.hidden=true;els.share.hidden=true}
function ensureReady(){if(!state.files.length)throw new Error('請先選擇文件。');const total=state.files.reduce((s,f)=>s+f.size,0);if(total>200*1024*1024)throw new Error('檔案總大小超過 200 MB 安全上限。')}
function loadScript(src,globalName){return new Promise((resolve,reject)=>{if(globalName&&window[globalName])return resolve();const existing=document.querySelector(`script[data-lib=\"${globalName}\"]`);if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',()=>reject(new Error(`${globalName} 載入失敗。`)),{once:true});return}const sc=document.createElement('script');sc.src=src;sc.async=true;sc.crossOrigin='anonymous';sc.dataset.lib=globalName;sc.onload=()=>resolve();sc.onerror=()=>reject(new Error(`${globalName} 載入失敗，請檢查網絡。`));document.head.appendChild(sc)})}
async function ensureLibraries(){await loadScript('https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js','PDFLib');if(['split','pdf2img'].includes(state.tool.id))await loadScript('https://unpkg.com/jszip@3.10.1/dist/jszip.min.js','JSZip')}
async function arrayBuffer(file){return await file.arrayBuffer()}
function parsePages(text,max){if(!text?.trim())return[];const out=[];for(const raw of text.split(',')){const p=raw.trim();if(!p)continue;if(p.includes('-')){const[a,b]=p.split('-').map(Number);if(!Number.isInteger(a)||!Number.isInteger(b)||a<1||b<a||b>max)throw new Error(`無效頁碼範圍：${p}`);for(let i=a;i<=b;i++)out.push(i-1)}else{const n=Number(p);if(!Number.isInteger(n)||n<1||n>max)throw new Error(`無效頁碼：${p}`);out.push(n-1)}}return out}
async function makePdfFromIndices(src,indices){const{PDFDocument}=window.PDFLib;const out=await PDFDocument.create();const pages=await out.copyPages(src,indices);pages.forEach(p=>out.addPage(p));return out}
async function processTool(){if(state.processing)return;try{ensureReady();state.processing=true;state.cancel=false;els.cancel.hidden=false;els.process.disabled=true;clearResult();setProgress(2,'載入 PDF engine…');await ensureLibraries();const fn=processors[state.tool.id];if(!fn)throw new Error('此工具未實作。');const result=await fn();if(state.cancel)throw new Error('已取消處理。');if(result?.blob){const url=URL.createObjectURL(result.blob);state.result={blob:result.blob,url};state.resultName=result.name;els.resultName.textContent=result.name;els.resultMeta.textContent=`${formatBytes(result.blob.size)} · 已在本機完成`;els.result.hidden=false;const file=new File([result.blob],result.name,{type:result.blob.type});els.share.hidden=!(navigator.canShare&&navigator.canShare({files:[file]}));setProgress(100,'完成');setTimeout(clearProgress,700)}}catch(e){clearProgress();toast(e.message||String(e))}finally{state.processing=false;els.cancel.hidden=true;els.process.disabled=false}}
function pdfResult(bytes,name){return{blob:new Blob([bytes],{type:'application/pdf'}),name}}
const processors={
async merge(){const{PDFDocument}=PDFLib;const out=await PDFDocument.create();for(let i=0;i<state.files.length;i++){if(state.cancel)break;setProgress(5+85*i/state.files.length,`合併 ${i+1}/${state.files.length}`);const src=await PDFDocument.load(await arrayBuffer(state.files[i]));const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}return pdfResult(await out.save(),'merged.pdf')},
async split(){if(!window.JSZip)throw new Error('ZIP library 尚未載入。');const{PDFDocument}=PDFLib,f=state.files[0],src=await PDFDocument.load(await arrayBuffer(f)),max=src.getPageCount(),chunks=$('#ranges').value.split(',').map(x=>x.trim()).filter(Boolean);if(!chunks.length)throw new Error('請輸入分割範圍。');const zip=new JSZip();for(let i=0;i<chunks.length;i++){if(state.cancel)break;const idx=parsePages(chunks[i],max);const out=await makePdfFromIndices(src,idx);zip.file(`${safeName(f.name)}_part_${String(i+1).padStart(2,'0')}.pdf`,await out.save());setProgress(10+65*(i+1)/chunks.length,`建立第 ${i+1}/${chunks.length} 份`)}setProgress(82,'建立 ZIP…');const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:5}},m=>setProgress(82+m.percent*.15,'壓縮 ZIP…'));return{blob,name:`${safeName(f.name)}_split.zip`}},
async extract(){const{PDFDocument}=PDFLib,f=state.files[0],src=await PDFDocument.load(await arrayBuffer(f)),idx=parsePages($('#pages').value,src.getPageCount());if(!idx.length)throw new Error('請輸入要提取的頁碼。');const out=await makePdfFromIndices(src,idx);return pdfResult(await out.save(),`${safeName(f.name)}_extracted.pdf`)},
async delete(){const{PDFDocument}=PDFLib,f=state.files[0],src=await PDFDocument.load(await arrayBuffer(f)),del=new Set(parsePages($('#pages').value,src.getPageCount()));if(!del.size)throw new Error('請輸入要刪除的頁碼。');const keep=src.getPageIndices().filter(i=>!del.has(i));if(!keep.length)throw new Error('不能刪除全部頁面。');const out=await makePdfFromIndices(src,keep);return pdfResult(await out.save(),`${safeName(f.name)}_pages_removed.pdf`)},
async rotate(){const{PDFDocument,degrees}=PDFLib,f=state.files[0],doc=await PDFDocument.load(await arrayBuffer(f)),text=$('#pages').value,idx=text.trim()?parsePages(text,doc.getPageCount()):doc.getPageIndices(),angle=Number($('#angle').value);idx.forEach((pi,i)=>{const p=doc.getPage(pi);p.setRotation(degrees((p.getRotation().angle+angle)%360));if(i%10===0)setProgress(10+65*(i+1)/idx.length,'旋轉頁面…')});return pdfResult(await doc.save(),`${safeName(f.name)}_rotated.pdf`)},
async reorder(){const{PDFDocument}=PDFLib,f=state.files[0],src=await PDFDocument.load(await arrayBuffer(f)),n=src.getPageCount(),idx=parsePages($('#order').value,n);if(idx.length!==n||new Set(idx).size!==n)throw new Error(`新次序必須包含 1-${n} 每一頁一次。`);const out=await makePdfFromIndices(src,idx);return pdfResult(await out.save(),`${safeName(f.name)}_reordered.pdf`)},
async img2pdf(){const{PDFDocument}=PDFLib,out=await PDFDocument.create(),mode=$('#pageSize').value,margin=Number($('#margin').value);for(let i=0;i<state.files.length;i++){if(state.cancel)break;const f=state.files[i],buf=await arrayBuffer(f),img=f.type==='image/png'?await out.embedPng(buf):await out.embedJpg(buf);let pw=img.width,ph=img.height;if(mode==='a4'){pw=595.28;ph=841.89}const page=out.addPage([pw,ph]),maxW=pw-margin*2,maxH=ph-margin*2,scale=Math.min(maxW/img.width,maxH/img.height,mode==='image'?1:Infinity),w=img.width*scale,h=img.height*scale;page.drawImage(img,{x:(pw-w)/2,y:(ph-h)/2,width:w,height:h});setProgress(8+80*(i+1)/state.files.length,`加入圖片 ${i+1}/${state.files.length}`)}return pdfResult(await out.save(),'images.pdf')},
async pdf2img(){if(!window.JSZip)throw new Error('ZIP library 尚未載入。');const pdfjs=await import('https://unpkg.com/pdfjs-dist@6.2.108/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://unpkg.com/pdfjs-dist@6.2.108/build/pdf.worker.min.mjs';const f=state.files[0],data=new Uint8Array(await arrayBuffer(f)),pdf=await pdfjs.getDocument({data,cMapUrl:'https://unpkg.com/pdfjs-dist@6.2.108/cmaps/',cMapPacked:true,standardFontDataUrl:'https://unpkg.com/pdfjs-dist@6.2.108/standard_fonts/',wasmUrl:'https://unpkg.com/pdfjs-dist@6.2.108/wasm/'}).promise,zip=new JSZip(),type=$('#imageType').value,scale=Number($('#scale').value);for(let n=1;n<=pdf.numPages;n++){if(state.cancel)break;const page=await pdf.getPage(n),viewport=page.getViewport({scale}),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{alpha:false});canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:ctx,viewport}).promise;const mime=type==='jpeg'?'image/jpeg':'image/png',blob=await new Promise(r=>canvas.toBlob(r,mime,type==='jpeg'?.88:undefined));zip.file(`page_${String(n).padStart(3,'0')}.${type==='jpeg'?'jpg':'png'}`,blob);canvas.width=1;canvas.height=1;page.cleanup();setProgress(5+70*n/pdf.numPages,`轉換頁面 ${n}/${pdf.numPages}`)}const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:4}},m=>setProgress(78+m.percent*.19,'建立 ZIP…'));return{blob,name:`${safeName(f.name)}_images.zip`}},
async watermark(){const{PDFDocument,degrees}=PDFLib,f=state.files[0],doc=await PDFDocument.load(await arrayBuffer(f)),text=$('#watermarkText').value.trim();if(!text)throw new Error('請輸入水印文字。');const opacity=Math.max(.05,Math.min(.9,Number($('#opacity').value)||.18)),rot=Number($('#wmRotate').value),pngBytes=await textToPng(text,opacity),img=await doc.embedPng(pngBytes),pages=doc.getPages();pages.forEach((p,i)=>{const{width,height}=p.getSize(),target=Math.min(width*.72,520),ratio=img.height/img.width,h=target*ratio;p.drawImage(img,{x:(width-target)/2,y:(height-h)/2,width:target,height:h,rotate:degrees(rot),opacity:1});if(i%8===0)setProgress(10+70*(i+1)/pages.length,'加入水印…')});return pdfResult(await doc.save(),`${safeName(f.name)}_watermarked.pdf`)},
async pagenum(){const{PDFDocument,StandardFonts,rgb}=PDFLib,f=state.files[0],doc=await PDFDocument.load(await arrayBuffer(f)),font=await doc.embedFont(StandardFonts.Helvetica),pages=doc.getPages(),pos=$('#position').value,fmt=$('#numFormat').value;pages.forEach((p,i)=>{const n=i+1,total=pages.length,text=fmt==='n-total'?`${n} / ${total}`:fmt==='page-n'?`Page ${n}`:`${n}`,size=9,{width,height}=p.getSize(),tw=font.widthOfTextAtSize(text,size);let x=(width-tw)/2,y=16;if(pos==='bottom-right')x=width-tw-22;if(pos==='top-center')y=height-24;p.drawText(text,{x,y,size,font,color:rgb(.35,.39,.45),opacity:.92})});return pdfResult(await doc.save(),`${safeName(f.name)}_numbered.pdf`)},
async metadata(){const{PDFDocument}=PDFLib,f=state.files[0],doc=await PDFDocument.load(await arrayBuffer(f),{updateMetadata:false});doc.setTitle('');doc.setAuthor('');doc.setSubject('');doc.setKeywords([]);doc.setCreator('');doc.setProducer('');doc.setModificationDate(new Date());return pdfResult(await doc.save({updateFieldAppearances:false}),`${safeName(f.name)}_metadata_cleaned.pdf`)},
async info(){const{PDFDocument}=PDFLib,f=state.files[0],doc=await PDFDocument.load(await arrayBuffer(f),{updateMetadata:false}),first=doc.getPages()[0]?.getSize(),data=[['檔名',f.name],['大小',formatBytes(f.size)],['頁數',String(doc.getPageCount())],['第一頁尺寸',first?`${first.width.toFixed(1)} × ${first.height.toFixed(1)} pt`:'—'],['Title',doc.getTitle()||'—'],['Author',doc.getAuthor()||'—'],['Subject',doc.getSubject()||'—'],['Creator',doc.getCreator()||'—'],['Producer',doc.getProducer()||'—']];$('#infoOutput').innerHTML=data.map(([k,v])=>`<div style="display:grid;grid-template-columns:105px 1fr;gap:8px;padding:5px 0;border-bottom:1px solid var(--line)"><b>${escapeHtml(k)}</b><span style="overflow-wrap:anywhere">${escapeHtml(v)}</span></div>`).join('');clearProgress();return null}
};
async function textToPng(text,opacity){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),dpr=Math.min(devicePixelRatio||1,2),fs=64*dpr;ctx.font=`800 ${fs}px -apple-system,BlinkMacSystemFont,"PingFang HK","PingFang TC","Noto Sans TC",sans-serif`;const m=ctx.measureText(text),pad=38*dpr;canvas.width=Math.ceil(m.width+pad*2);canvas.height=Math.ceil(fs*1.65);ctx.font=`800 ${fs}px -apple-system,BlinkMacSystemFont,"PingFang HK","PingFang TC","Noto Sans TC",sans-serif`;ctx.textBaseline='middle';ctx.textAlign='center';ctx.fillStyle=`rgba(110,20,30,${opacity})`;ctx.fillText(text,canvas.width/2,canvas.height/2);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));return new Uint8Array(await blob.arrayBuffer())}
function downloadResult(){if(!state.result)return;const a=document.createElement('a');a.href=state.result.url;a.download=state.resultName;document.body.appendChild(a);a.click();a.remove()}
async function shareResult(){if(!state.result)return;const file=new File([state.result.blob],state.resultName,{type:state.result.blob.type});try{await navigator.share({files:[file],title:state.resultName})}catch(e){if(e.name!=='AbortError')toast('此 browser 未能分享文件。')}}
els.search.addEventListener('input',e=>renderTools(e.target.value));els.close.onclick=closeDialog;els.drop.onclick=()=>els.input.click();els.drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();els.input.click()}};els.input.onchange=e=>{addFiles(e.target.files);e.target.value=''};['dragenter','dragover'].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.remove('dragging')}));els.drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));els.process.onclick=processTool;els.cancel.onclick=()=>{state.cancel=true;toast('會在目前步驟完成後停止。')};els.download.onclick=downloadResult;els.share.onclick=shareResult;els.dialog.addEventListener('cancel',e=>{if(state.processing){e.preventDefault();toast('請先取消處理')}});els.theme.onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('theme',next)};document.documentElement.dataset.theme=localStorage.getItem('theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e});els.install.onclick=async()=>{if(state.deferredPrompt){state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null}else toast(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'iPhone：Safari 分享 → 加入主畫面':'使用 browser 選單 → 安裝 / 加入主畫面')};if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}renderTools();
